// <auto-generated />
using System;
using ClinicalHealthcare.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicalHealthcare.Infrastructure.PgMigrations.Migrations
{
    [DbContext(typeof(ClinicalDbContext))]
    [Migration("20260514081740_ClinicalEntities")]
    partial class ClinicalEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicalHealthcare.Infrastructure.Entities.ConflictFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResolvedByStaffId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Value1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_ConflictFlags_PatientId");

                    b.ToTable("ConflictFlags");
                });

            modelBuilder.Entity("ClinicalHealthcare.Infrastructure.Entities.ExtractedClinicalField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExtractedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExtractionJobId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("FieldType")
                        .HasColumnType("integer");

                    b.Property<string>("FieldValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_ExtractedClinicalFields_DocumentId");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_ExtractedClinicalFields_PatientId");

                    b.ToTable("ExtractedClinicalFields", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExtractedClinicalFields_ConfidenceScore", "\"ConfidenceScore\" >= 0.0 AND \"ConfidenceScore\" <= 1.0");
                        });
                });

            modelBuilder.Entity("ClinicalHealthcare.Infrastructure.Entities.MedicalCodeSuggestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("CodeType")
                        .HasColumnType("integer");

                    b.Property<string>("CommittedCode")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<bool>("LowConfidenceFlag")
                        .HasColumnType("boolean");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SuggestedCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("IX_MedicalCodeSuggestions_PatientId");

                    b.ToTable("MedicalCodeSuggestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedicalCodeSuggestions_ConfidenceScore", "\"ConfidenceScore\" >= 0.0 AND \"ConfidenceScore\" <= 1.0");

                            t.HasCheckConstraint("CK_MedicalCodeSuggestions_TrustFirst", "\"Status\" != 1 OR \"VerifiedById\" IS NOT NULL");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
